#:schema node_modules/wrangler/config-schema.json
name = "videos-allowed"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
LIST_ID = "ed272cd9-5766-403f-bf80-0616b7d391a0"
